# The overall format is standard TOML format, v0.5.0.
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[39,)" #mandatory
issueTrackerURL="https://github.com/Sinhika/SterlingAndBlack/issues"
license="LGPL 3"

[[mods]]
modId="sterlingblack"
version="${file.jarVersion}"
displayName="akkamaddi's Sterling and Black"
updateJSONURL="https://raw.githubusercontent.com/Sinhika/SterlingAndBlack/1.18/update.json"
displayURL="CurseForge URL"
credits="Thanks to akkamaddi for creating the original mod and to Sinhika for porting and maintaining it."
authors="akkamaddi, Sinhika"
description='''Sterling Steel and Black Silver alloys to Zot's Only Silver. Simple Ores2:Fusion add-on
'''

[[dependencies.sterlingblack]]
    modId="forge"
    mandatory=true
    versionRange="[39.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sterlingblack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.sterlingblack]]
    modId="simplecorelib"
    mandatory=true
    versionRange="[1.18.1-4.0.1.0, 1.18.2)"
    ordering="NONE"
    side="BOTH"    

[[dependencies.sterlingblack]]
    modId="fusion"
    mandatory=true
    versionRange="[1.18.1-4.0.1.0, 1.18.2)"
    ordering="NONE"
    side="BOTH"    

[[dependencies.sterlingblack]]
    modId="onlysilver"
    mandatory=false
    versionRange="[1.18.1-4.0.0.0, 1.18.2)"
    ordering="BEFORE"
    side="BOTH"    

#[[dependencies.sterlingblack]]
#        modId="silents_mechanisms"
#        mandatory=false
#        versionRange="[0.8.9,)"
#        ordering="BEFORE"
#        side="BOTH"
#        
#[[dependencies.sterlingblack]]
#        modId="silentgear"
#        mandatory=false
#        versionRange="[2.5.2,)"
#        ordering="BEFORE"
#        side="BOTH"
#     
