# The overall format is standard TOML format, v0.5.0.
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[31,)" #mandatory
issueTrackerURL="https://github.com/Sinhika/simplemod/issues"

[[mods]]
modId="sterlingblack"
version="${version}"
displayName="Sterling and Black"
updateJSONURL="https://raw.githubusercontent.com/Sinhika/SterlingAndBlack/1.15/update.json"
displayURL="CurseForge URL"
credits="Thanks to akkamaddi for creating the original mod and to Sinhika for porting and maintaining it."
authors="akkamaddi, Sinhika"
description='''Sterling Steel and Black Silver alloys to Zot's Only Silver. Simple Ores2:Fusion add-on
'''

[[dependencies.sterlingblack]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.26,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sterlingblack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.sterlingblack]]
    modId="simpleores"
    mandatory=true
    versionRange="[1.15.2-2.1.8.0,]"
    ordering="NONE"
    side="BOTH"    

[[dependencies.sterlingblack]]
    modId="fusion"
    mandatory=true
    versionRange="[1.15.2-2.5.12,]"
    ordering="NONE"
    side="BOTH"    

[[dependencies.sterlingblack]]
    modId="onlysilver"
    mandatory=false
    versionRange="[1.15.2-2.1.0,]"
    ordering="BEFORE"
    side="BOTH"    
    